### PR TITLE
feat: add call recorder timer take 2

### PR DESCRIPTION
**Pull request by dane-stevens**
#128

### CODE REVIEW

**Comment by dane-stevens** [comment]
@kentcdodds this one should be good! I'm new to contributing to larger projects, so feel free to give me any tips on working with shared repos.

**Review by kentcdodds — APPROVED** [review]
Perfect, thanks!

**Comment by kentcdodds** [comment]
In the future, you might consider installing prettier in your editor so you can auto-format your code following my prettier configuration :)

Thanks a lot for the contribution!

**Comment by dane-stevens** [comment]
Will do! I'm learing typescript on the fly as well, so I will update the hook to use typescript once I figure out how to get it working.

**Comment by kentcdodds** [comment]
That would be super 👍

**Pull request merged**
