### PR TITLE
`that take some time` → `that can take some time`

### PR DESCRIPTION
**Pull request by jasikpark**

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks for this! It reminds me that I improved local development quite a bit and it's not as complicated anymore. I'll go ahead and update this now.

**Comment by kentcdodds** [comment]
Actually, I can still use your change :)

**Comment by jasikpark** [comment]
Oooh nice - I was sleuthing through to look at your site dev flow - I've really been wanting to improve the simplicity for hosting a simple blog that posts photos and text, like a basic WP blog but w/ git-backed content management... Though I then remembered that you decided to use `github.com` as your CMS 😆 

(currently tempted to just spin up a ghost blog)

**Comment by kentcdodds** [comment]
Yeah, the benefit of using GitHub as a CMS is that people can contribute fixes to it without me having to worry about user management etc. It's quite nice :)

**Pull request merged**
