### PR TITLE
Feature: add call recording timer

### PR DESCRIPTION
**Pull request by dane-stevens**
#128

### CODE REVIEW

**Comment by kentcdodds** [comment]
Oh snap! How cool!

Do you mind doing a quick screen recording showing me what this looks like? I don't currently deploy to a staging environment and would have to pull this down to test it out.

**Comment by dane-stevens** [comment]
Here it is! The timer has been sped up by 80% in the video. Works with pause/resume and re-recording. Colors change at 01:30 and 02:00


https://user-images.githubusercontent.com/12450895/145110581-f08c7861-598d-438a-a383-09c695213412.mp4

**Comment by kentcdodds** [comment]
This is epic! Love it. Thank you :)

I tried and failed to restore the original package-lock.json file. Not sure why I can't push from my local to your fork. Could you fix that yourself? I just don't like changes to the package-lock.json unless new deps are added/removed. Thanks!

**Comment by dane-stevens** [comment]
Sure can, I will pull that file in. Not sure why that happens. I think when I run `npm install` (I'm on linux) the package-lock.json file is a little different. I think i can add it to `./git/info/exclude` and not have my version get pushed

**Comment by dane-stevens** [comment]
Were you waiting on me for something still?

**Comment by kentcdodds** [comment]
Yeah, sorry, I don't want to commit any changes to the `package-lock.json`. Could you revert those changes?

I think the reason I can't push from my local to your PR is because you made it from your `main` branch. Otherwise I would fix this myself. Sorry.

**Comment by dane-stevens** [comment]
Ok, I pulled in the latest `package-lock.json` file from your `main` branch. The pull request is still showing the file has changed though.

**Comment by dane-stevens** [comment]
> Yeah, sorry, I don't want to commit any changes to the `package-lock.json`. Could you revert those changes?
> 
> I think the reason I can't push from my local to your PR is because you made it from your `main` branch. Otherwise I would fix this myself. Sorry.

In the future...what's the best way for me to do a pull request? Should I be creating a separate branch and requesting that?

**Comment by kentcdodds** [comment]
Yeah, a different branch is better (and more common).

Unfortunately this PR still has `package-lock.json` changes 😬

**Comment by kentcdodds** [comment]
If you're not sure how to fix it up, you could try making a new branch based on my `main` branch and make all the changes without installing.

**Pull request closed without merging**
